### teste get all contas
GET http://localhost:40000/contas HTTP/1.1
content-type: application/json
//Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE2NzQ3ODI5NzksInVzZXJuYW1lIjoicXdlIn0.SlYYCm8J6wlpb3i1jJcSvhSz6VjwKvzPOxza8P6-hzo

{    
    
}

### teste get by id
GET http://localhost:40000/conta/1 HTTP/1.1
content-type: application/json
//Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE2NzQ3ODI5NzksInVzZXJuYW1lIjoicXdlIn0.SlYYCm8J6wlpb3i1jJcSvhSz6VjwKvzPOxza8P6-hzo

{    
  
}

### teste insert
POST http://localhost:40000/conta HTTP/1.1
content-type: application/json
//Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE2NzQ3ODI5NzksInVzZXJuYW1lIjoicXdlIn0.SlYYCm8J6wlpb3i1jJcSvhSz6VjwKvzPOxza8P6-hzo

{    
    "banco": "santander",
    "agencia": "3",
    "conta_corrente": "asdg",
    "receber": 10,
    "pagar": 20,
    "deleted": false
}

### teste update by id
PUT http://localhost:40000/conta HTTP/1.1
content-type: application/json
//Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE2NzQ3ODI5NzksInVzZXJuYW1lIjoicXdlIn0.SlYYCm8J6wlpb3i1jJcSvhSz6VjwKvzPOxza8P6-hzo

{    
    "id": "1",
    "banco": "nubank",
    "agencia": "3",
    "conta_corrente": "ghjkkk",
    "receber": 40,
    "pagar": 10,
    "deleted": false
}

### teste delete by id
DELETE http://localhost:40000/conta/1 HTTP/1.1
content-type: application/json
//Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE2NzQ3ODI5NzksInVzZXJuYW1lIjoicXdlIn0.SlYYCm8J6wlpb3i1jJcSvhSz6VjwKvzPOxza8P6-hzo

{    
  
}